# Generated by Django 2.2.6 on 2019-11-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20191106_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
