# Generated by Django 2.2.6 on 2019-10-25 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ExpenseType',
                'verbose_name_plural': 'ExpenseTypes',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=50)),
                ('expense_amt', models.IntegerField()),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpenseType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.ExpenseType')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
