# Generated by Django 2.2.6 on 2019-10-14 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
